#!/bin/bash

source ".env"

# @Function: migration
# @Param: $1 (filename)
migration () {
	filename=$1
	flag=""

	echo "Try to Execute Migration [$filename]"

	if [ -f $filename ]; then
		output=$(export PGPASSWORD="$DATABASE_PASS" && psql -U $DATABASE_USER -h $DATABASE_HOST -d $DATABASE_NAME < $filename)
	else
		echo "Migration file doesn't exist"
	fi
}

# @Function: constructor
# @Param: $1 (filename or folder)
# @Param: $2 (all or empty)
constructor () {
	filepath=$1
	filename=$1
	command=$2

	if [[ "$command" == "all" ]]; then
		FILES="$filepath/*"
		for file in $FILES; do
			migration $file
		done
		exit 0
	fi

	migration $filename
	exit 0
}

constructor $1 $2
